/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

/**
 *
 * @author Idavor
 */
public class OptionsUIAnt extends javax.swing.JFrame {

    /**
     * Creates new form OptionsUI
     */
    public OptionsUIAnt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        initCountField = new javax.swing.JTextField();
        colonyCountField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        randomFactorField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        detoriationField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        distancePriorityField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Opcje -Algorytm Kolonii Mrówek");

        jLabel4.setText("Ilość podstawowa");

        jLabel5.setText("Wielkość kolonii");

        initCountField.setText("200");
        initCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initCountFieldActionPerformed(evt);
            }
        });

        colonyCountField.setText("1000");
        colonyCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonyCountFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        randomFactorField.setText("0.4");
        randomFactorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomFactorFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Współ. losowy");

        detoriationField.setText("0.7");
        detoriationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detoriationFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Ulatnianie");

        distancePriorityField.setText("0.7");
        distancePriorityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distancePriorityFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Priorytet heur.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(distancePriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(randomFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(initCountField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(colonyCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(detoriationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(initCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(colonyCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(randomFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(detoriationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(distancePriorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initCountFieldActionPerformed

    private void colonyCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonyCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colonyCountFieldActionPerformed

    private void randomFactorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomFactorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomFactorFieldActionPerformed

    private void detoriationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detoriationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detoriationFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        if (MainGUI.optRouter == 0) {
            MainGUI.opt0.colonyCount = Integer.parseInt(this.colonyCountField.getText());
            MainGUI.opt0.initialAntCount = Integer.parseInt(this.initCountField.getText());
            MainGUI.opt0.pheromoneDetoriation = Double.parseDouble(this.detoriationField.getText());
            MainGUI.opt0.randomFactor = Double.parseDouble(this.randomFactorField.getText());

        }
        if (MainGUI.optRouter == 1) {
            MainGUI.opt1.colonyCount= Integer.parseInt(this.colonyCountField.getText());
            MainGUI.opt1.initialAntCount = Integer.parseInt(this.initCountField.getText());
            MainGUI.opt1.pheromoneDetoriation = Double.parseDouble(this.detoriationField.getText());
            MainGUI.opt1.randomFactor = Double.parseDouble(this.randomFactorField.getText());
            
        }
        if (MainGUI.optRouter == 2) {
            MainGUI.opt2.colonyCount = Integer.parseInt(this.colonyCountField.getText());
            MainGUI.opt2.initialAntCount = Integer.parseInt(this.initCountField.getText());
            MainGUI.opt2.pheromoneDetoriation = Double.parseDouble(this.detoriationField.getText());
            MainGUI.opt2.randomFactor = Double.parseDouble(this.randomFactorField.getText());
            
        }
        if (MainGUI.optRouter == 3) {
            MainGUI.opt3.colonyCount = Integer.parseInt(this.colonyCountField.getText());
            MainGUI.opt3.initialAntCount = Integer.parseInt(this.initCountField.getText());
            MainGUI.opt3.pheromoneDetoriation = Double.parseDouble(this.detoriationField.getText());
            MainGUI.opt3.randomFactor = Double.parseDouble(this.randomFactorField.getText());
            
        }
        
        this.setVisible(false);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void distancePriorityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distancePriorityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distancePriorityFieldActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        setTexts();
    }//GEN-LAST:event_formWindowActivated
    public void setTexts() {

        String cc = Integer.toString(MainGUI.opt0.colonyCount);
        String ic = Integer.toString(MainGUI.opt0.initialAntCount);
        String pd = Double.toString(MainGUI.opt0.pheromoneDetoriation);
        String rf = Double.toString(MainGUI.opt0.randomFactor);
        String dp = Double.toString(MainGUI.opt0.distancePriority);
        
        if (MainGUI.optRouter == 1) {
            cc = Integer.toString(MainGUI.opt1.colonyCount);
            ic = Integer.toString(MainGUI.opt1.initialAntCount);
            pd = Double.toString(MainGUI.opt1.pheromoneDetoriation);
            rf = Double.toString(MainGUI.opt1.randomFactor);
            dp = Double.toString(MainGUI.opt1.distancePriority);
        }
        if (MainGUI.optRouter == 2) {
            cc = Integer.toString(MainGUI.opt2.colonyCount);
            ic = Integer.toString(MainGUI.opt2.initialAntCount);
            pd = Double.toString(MainGUI.opt2.pheromoneDetoriation);
            rf = Double.toString(MainGUI.opt2.randomFactor);
            dp = Double.toString(MainGUI.opt2.distancePriority);
            
        }
        if (MainGUI.optRouter == 3) {
            cc = Integer.toString(MainGUI.opt3.colonyCount);
            ic = Integer.toString(MainGUI.opt3.initialAntCount);
            pd = Double.toString(MainGUI.opt3.pheromoneDetoriation);
            rf = Double.toString(MainGUI.opt3.randomFactor);
            dp = Double.toString(MainGUI.opt3.distancePriority);
            
        }
        this.colonyCountField.setText(cc);
        this.initCountField.setText(ic);
        this.detoriationField.setText(pd);
        this.randomFactorField.setText(rf);
        this.distancePriorityField.setText(dp);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsUIAnt().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField colonyCountField;
    private javax.swing.JTextField detoriationField;
    private javax.swing.JTextField distancePriorityField;
    private javax.swing.JTextField initCountField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField randomFactorField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
