/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

/**
 *
 * @author Idavor
 */
public class OptionsUIGenetic extends javax.swing.JFrame {

    /**
     * Creates new form OptionsUI
     */
    public OptionsUIGenetic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        heurBox = new javax.swing.JCheckBox();
        pmxButton = new javax.swing.JRadioButton();
        oxButton = new javax.swing.JRadioButton();
        splitButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regularButton = new javax.swing.JRadioButton();
        moveButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        populationField = new javax.swing.JTextField();
        generationField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tourneeButton = new javax.swing.JRadioButton();
        rouletteButton = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mutationProbField = new javax.swing.JTextField();
        crossPobField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Opcje -Algorytm Ewolucyjny");

        heurBox.setText("Heurystyka");

        buttonGroup1.add(pmxButton);
        pmxButton.setSelected(true);
        pmxButton.setText("PMX");
        pmxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmxButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(oxButton);
        oxButton.setText("OX");

        buttonGroup1.add(splitButton);
        splitButton.setText("Split");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Krzyżowanie");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mutacja");

        buttonGroup2.add(regularButton);
        regularButton.setSelected(true);
        regularButton.setText("Równomierna");
        regularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(moveButton);
        moveButton.setText("Przesunięcie");

        jLabel4.setText("Populacja");

        jLabel5.setText("Liczba Generacji");

        populationField.setText("100");
        populationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populationFieldActionPerformed(evt);
            }
        });

        generationField.setText("100");
        generationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generationFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Wybór rodziców");

        buttonGroup3.add(tourneeButton);
        tourneeButton.setText("Turniej");

        buttonGroup3.add(rouletteButton);
        rouletteButton.setSelected(true);
        rouletteButton.setText("Ruletka");
        rouletteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rouletteButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Prawdop.");

        jLabel8.setText("Prawdop.");

        mutationProbField.setText("0.01");
        mutationProbField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutationProbFieldActionPerformed(evt);
            }
        });

        crossPobField.setText("0.8");
        crossPobField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossPobFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(heurBox)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(moveButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(41, 41, 41)
                                    .addComponent(populationField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(generationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(rouletteButton))
                            .addComponent(tourneeButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(regularButton))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mutationProbField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(crossPobField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(oxButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pmxButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(splitButton))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(heurBox)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pmxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(splitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regularButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crossPobField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mutationProbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tourneeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rouletteButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(populationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(generationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pmxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmxButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmxButtonActionPerformed

    private void regularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regularButtonActionPerformed

    private void populationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_populationFieldActionPerformed

    private void generationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generationFieldActionPerformed

    private void mutationProbFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutationProbFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mutationProbFieldActionPerformed

    private void crossPobFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossPobFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crossPobFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (MainGUI.optRouter == 4) {

             MainGUI.opt.heuristic = heurBox.isSelected();
             if(pmxButton.isSelected())
                MainGUI.opt.crossing = 0;
             if(oxButton.isSelected())
                 MainGUI.opt.crossing = 1;
             if(splitButton.isSelected())
                 MainGUI.opt.crossing = 2;
             
             if(regularButton.isSelected())
                 MainGUI.opt.mutation = 0;
             if(moveButton.isSelected())
                 MainGUI.opt.mutation = 1;
             
             if(tourneeButton.isSelected())
                 MainGUI.opt.selection = 0;
             if(rouletteButton.isSelected())
                 MainGUI.opt.selection = 1;
                         
             MainGUI.opt.population = Integer.parseInt(populationField.getText()); 
             MainGUI.opt.generations = Integer.parseInt(generationField.getText()); 
             MainGUI.opt.crossP = Double.parseDouble(crossPobField.getText()); 
             MainGUI.opt.mutationP = Double.parseDouble(mutationProbField.getText()); 
             

        }
        if (MainGUI.optRouter == 4) {
                         MainGUI.opt.heuristic = heurBox.isSelected();
             if(pmxButton.isSelected())
                MainGUI.opt1.crossing = 0;
             if(oxButton.isSelected())
                 MainGUI.opt1.crossing = 1;
             if(splitButton.isSelected())
                 MainGUI.opt1.crossing = 2;
             
             if(regularButton.isSelected())
                 MainGUI.opt1.mutation = 0;
             if(moveButton.isSelected())
                 MainGUI.opt1.mutation = 1;
             
             if(tourneeButton.isSelected())
                 MainGUI.opt1.selection = 0;
             if(rouletteButton.isSelected())
                 MainGUI.opt1.selection = 1;
                         
             MainGUI.opt1.population = Integer.parseInt(populationField.getText()); 
             MainGUI.opt1.generations = Integer.parseInt(generationField.getText()); 
             MainGUI.opt1.crossP = Integer.parseInt(crossPobField.getText()); 
             MainGUI.opt1.mutationP = Integer.parseInt(mutationProbField.getText()); 
        }
        if (MainGUI.optRouter == 4) {
                         MainGUI.opt2.heuristic = heurBox.isSelected();
             if(pmxButton.isSelected())
                MainGUI.opt2.crossing = 0;
             if(oxButton.isSelected())
                 MainGUI.opt2.crossing = 1;
             if(splitButton.isSelected())
                 MainGUI.opt2.crossing = 2;
             
             if(regularButton.isSelected())
                 MainGUI.opt2.mutation = 0;
             if(moveButton.isSelected())
                 MainGUI.opt2.mutation = 1;
             
             if(tourneeButton.isSelected())
                 MainGUI.opt2.selection = 0;
             if(rouletteButton.isSelected())
                 MainGUI.opt2.selection = 1;
                         
             MainGUI.opt2.population = Integer.parseInt(populationField.getText()); 
             MainGUI.opt2.generations = Integer.parseInt(generationField.getText()); 
             MainGUI.opt2.crossP = Integer.parseInt(crossPobField.getText()); 
             MainGUI.opt2.mutationP = Integer.parseInt(mutationProbField.getText()); 
        }
        if (MainGUI.optRouter == 4) {
                         MainGUI.opt3.heuristic = heurBox.isSelected();
             if(pmxButton.isSelected())
                MainGUI.opt3.crossing = 0;
             if(oxButton.isSelected())
                 MainGUI.opt3.crossing = 1;
             if(splitButton.isSelected())
                 MainGUI.opt3.crossing = 2;
             
             if(regularButton.isSelected())
                 MainGUI.opt3.mutation = 0;
             if(moveButton.isSelected())
                 MainGUI.opt3.mutation = 1;
             
             if(tourneeButton.isSelected())
                 MainGUI.opt3.selection = 0;
             if(rouletteButton.isSelected())
                 MainGUI.opt3.selection = 1;
                         
             MainGUI.opt3.population = Integer.parseInt(populationField.getText()); 
             MainGUI.opt3.generations = Integer.parseInt(generationField.getText()); 
             MainGUI.opt3.crossP = Integer.parseInt(crossPobField.getText()); 
             MainGUI.opt3.mutationP = Integer.parseInt(mutationProbField.getText()); 
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void rouletteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rouletteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rouletteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsUIGenetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsUIGenetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsUIGenetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsUIGenetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsUIGenetic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField crossPobField;
    private javax.swing.JTextField generationField;
    private javax.swing.JCheckBox heurBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton moveButton;
    private javax.swing.JTextField mutationProbField;
    private javax.swing.JRadioButton oxButton;
    private javax.swing.JRadioButton pmxButton;
    private javax.swing.JTextField populationField;
    private javax.swing.JRadioButton regularButton;
    private javax.swing.JRadioButton rouletteButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton splitButton;
    private javax.swing.JRadioButton tourneeButton;
    // End of variables declaration//GEN-END:variables
}
