/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pathfinder;

/**
 *
 * @author Idavor
 */
public class OptionsUIAnt extends javax.swing.JFrame {

    /**
     * Creates new form OptionsUI
     */
    public OptionsUIAnt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        heuristicCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        initCountField = new javax.swing.JTextField();
        colonyCountField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        randomFactorField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        detoriationField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Opcje -Algorytm Kolonii Mrówek");

        heuristicCheckBox.setText("Heurystyka");

        jLabel4.setText("Ilość podstawowa");

        jLabel5.setText("Wielkość kolonii");

        initCountField.setText("200");
        initCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initCountFieldActionPerformed(evt);
            }
        });

        colonyCountField.setText("100");
        colonyCountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colonyCountFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Zapisz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        randomFactorField.setText("0.4");
        randomFactorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomFactorFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Współ. losowy");

        detoriationField.setText("0.7");
        detoriationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detoriationFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Ulatnianie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(randomFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(initCountField))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(colonyCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(heuristicCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(detoriationField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(saveButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(heuristicCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(initCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(colonyCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(randomFactorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(detoriationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initCountFieldActionPerformed

    private void colonyCountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colonyCountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colonyCountFieldActionPerformed

    private void randomFactorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomFactorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_randomFactorFieldActionPerformed

    private void detoriationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detoriationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detoriationFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (MainGUI.optRouter == 0) {
            MainGUI.opt.colonyCount = Integer.parseInt(colonyCountField.getText());
            MainGUI.opt.initialAntCount = Integer.parseInt(initCountField.getText());
            MainGUI.opt.pheromoneDetoriation = Double.parseDouble(detoriationField.getText());
            MainGUI.opt.randomFactor = Double.parseDouble(randomFactorField.getText());
        }
        if (MainGUI.optRouter == 1) {
            MainGUI.opt1.colonyCount = Integer.parseInt(colonyCountField.getText());
            MainGUI.opt1.initialAntCount = Integer.parseInt(initCountField.getText());
            MainGUI.opt1.pheromoneDetoriation = Double.parseDouble(detoriationField.getText());
            MainGUI.opt1.randomFactor = Double.parseDouble(randomFactorField.getText());
        }
        if (MainGUI.optRouter == 2) {
            MainGUI.opt2.colonyCount = Integer.parseInt(colonyCountField.getText());
            MainGUI.opt2.initialAntCount = Integer.parseInt(initCountField.getText());
            MainGUI.opt2.pheromoneDetoriation = Double.parseDouble(detoriationField.getText());
            MainGUI.opt2.randomFactor = Double.parseDouble(randomFactorField.getText());
        }
        if (MainGUI.optRouter == 3) {
            MainGUI.opt3.colonyCount = Integer.parseInt(colonyCountField.getText());
            MainGUI.opt3.initialAntCount = Integer.parseInt(initCountField.getText());
            MainGUI.opt3.pheromoneDetoriation = Double.parseDouble(detoriationField.getText());
            MainGUI.opt3.randomFactor = Double.parseDouble(randomFactorField.getText());
        }
      
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsUIAnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsUIAnt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField colonyCountField;
    private javax.swing.JTextField detoriationField;
    private javax.swing.JCheckBox heuristicCheckBox;
    private javax.swing.JTextField initCountField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField randomFactorField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
